// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {check} from '../models';
import {report} from '../models';

export function Cancel():Promise<void>;

export function Info():Promise<main.AppInfo>;

export function Quit():Promise<void>;

export function Run(arg1:string,arg2:main.RunOptions):Promise<check.Result>;

export function SaveReport(arg1:string,arg2:string):Promise<string>;

export function Summarize(arg1:Array<check.Result>):Promise<report.Summary>;
