// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Run(arg1, arg2) {
  return window['go']['main']['App']['Run'](arg1, arg2);
}

export function SaveReport(arg1, arg2) {
  return window['go']['main']['App']['SaveReport'](arg1, arg2);
}

export function Summarize(arg1) {
  return window['go']['main']['App']['Summarize'](arg1);
}
